config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IdentityPython/pyFF:
      branch: master
      repo: https://github.com/IdentityPython/pyFF
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IdentityPython/pyFF git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-brown-cow.sh
        container: qc.acc_silly-lime-elephant
  QC.Doc:
    repos:
      github.com/IdentityPython/pyFF find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-saffron-kingfisher.sh
        container: qc.doc_stealthy-lemon-quetzal
      github.com/IdentityPython/pyFF git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-tangerine-buzzard.sh
        container: qc.doc_scummy-white-monster
      github.com/IdentityPython/pyFF markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-silver-devil.sh
        container: qc.doc_skinny-taupe-dogfish
      github.com/IdentityPython/pyFF restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cerulean-hyrax.sh
        container: qc.doc_pasty-linen-tapir
  QC.Lic:
    repos:
      github.com/IdentityPython/pyFF licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cerulean-chicken.sh
        container: qc.lic_skinny-violet-squirt
  QC.Sec:
    repos:
      github.com/IdentityPython/pyFF bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-lavender-boar.sh
        container: qc.sec_smelly-persimmon-dane
  QC.Sty:
    repos:
      github.com/IdentityPython/pyFF flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-firebrick-markhor.sh
        container: qc.sty_cranky-red-scorpion
  QC.Uni:
    repos:
      github.com/IdentityPython/pyFF pytest:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amber-meerkat.sh
        container: qc.uni_geeky-persimmon-salamander
  QC.Ver:
    repos:
      github.com/IdentityPython/pyFF get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-smalt-mandrill.sh
        container: qc.ver_flaky-ruby-shark
timeout: 5400
