config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IdentityPython/pyFF:
      branch: master
      repo: https://github.com/IdentityPython/pyFF
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IdentityPython/pyFF git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-copper-walrus.sh
        container: qc.acc_surly-gold-chin
  QC.Doc:
    repos:
      github.com/IdentityPython/pyFF find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-platinum-wasp.sh
        container: qc.doc_hasty-xanthic-vole
      github.com/IdentityPython/pyFF git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-violet-scorpion.sh
        container: qc.doc_jumpy-cream-cichlid
      github.com/IdentityPython/pyFF markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-emerald-dormouse.sh
        container: qc.doc_leaky-blue-bongo
      github.com/IdentityPython/pyFF restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-orange-dane.sh
        container: qc.doc_shaky-pear-fossa
  QC.Lic:
    repos:
      github.com/IdentityPython/pyFF licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-ochre-emu.sh
        container: qc.lic_skinny-cornflower-pig
  QC.Sec:
    repos:
      github.com/IdentityPython/pyFF bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-pear-hummingbird.sh
        container: qc.sec_wheezy-dandelion-neanderthal
  QC.Sty:
    repos:
      github.com/IdentityPython/pyFF flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-rust-cougar.sh
        container: qc.sty_nippy-vermilion-magpie
  QC.Uni:
    repos:
      github.com/IdentityPython/pyFF pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-brown-squid.sh
        container: qc.uni_sickly-viridian-bulldog
  QC.Ver:
    repos:
      github.com/IdentityPython/pyFF get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ultramarine-millipede.sh
        container: qc.ver_bumpy-lilac-axolotl
timeout: 5400
